# Practice 8
## Program 1: Students, subjects and grades

In [22]:
# Request the number of students in the class 
number_of_students = int(input("Introduce the number of students: "))
while number_of_students>50:
    number_of_students = int(input("It should be lower than 50. Introduce the number of students"))
else:
  valid_input = True

# Request the number of subjects 
number_of_subjects = int(input("Introduce the number of subjects: "))
while number_of_subjects>8:
    number_of_subjects = int(input("It should be lower than 8. Introduce the number of subjects"))
else:
  valid_input = True

print("==================") 
import numpy as np

#We create empty lists
l_students = []
l_subjects = []

#Introduce the name of the students
for i in range(number_of_students):
    current_name = input(f"Name of the student {i+1}: ")
    l_students.append(current_name)

print("==================")    
    
#Introduce the name of the subjects
for i in range(number_of_subjects):
    current_subject = input(f"Name of the subject {i+1}: ")
    l_subjects.append(current_subject)
    
print(l_students)
print(l_subjects)

grades_matrix = []

for i in range(number_of_students):
 grades_matrix.append([0]*number_of_subjects)

#Fill the grades

for i in range(number_of_students):
    for x in range (number_of_subjects):
        grade=float(input(f"Please,enter the grade for the student {i+1} in the subject {x+1}: "))
        grades_matrix[i][x]=grade
        print(np.array(grades_matrix))
  
print("==================") 


print("\n")
print("MENU")
print("1) Average Grade - Subject")
print("2) Average Grade - Student")
print("3) Show Grades of all students")
print("4) Show grades of a student")
print("5) Sign Out")
      
options=[1,2,3,4,5]
chose=int(input("Please select an option: "))
while chose not in options:
      print("\n")
      print("Option no valid")
      print("\n")
      chose=int(input("Please select an option: "))
            
while True:
   #Option 1: Request the name of the subject
            
 if chose==1:
    import numpy as np      
    subject_name = input("Please, enter the name of the subject: ")
    while subject_name not in l_subjects:
     print("\n")
     print("Invalid input.This subject does not exist")
     print("\n")        
    else:
     position = l_subjects.index(subject_name)
     l_transpose = np.transpose(grades_matrix)
     average= np.mean(l_transpose[position])
     print("The average of this subject is:", average)    
        
     print("\n")
     chose=int(input("Please select an option: "))
        
 #Option 2: Request the name of the student           
 if chose==2:   

  
  student_name = input("Please, enter the student name: ")
 
  if student_name not in l_students:
    print("Invalid input.This student does no exist")

  else:
   position = l_students.index(student_name)
   average = np.mean(grades_matrix[position])
   print("The average of this student is:" ,average)

   print("\n")
   chose=int(input("Please select an option: ")) 

#Option 3: Display the table
 if chose==3:
  print("Summary")
  print("=====================")
  first_line ="{:10s}".format("Student")
  for subject in l_subjects:
    first_line = first_line + " " + "{:10s}".format(subject)
    print(first_line)
    
  for i in range(number_of_students):
    current_line ="{:10s}".format(l_students[i])
    for j in range(number_of_subjects):
     current_line = current_line + " " + "{:10s}".format(str(grades_matrix[i][j]))
     print(current_line)
    
#Option 4: Grades displayed
 if chose==4:
    sub=input("Please enter the name of the student: ")
    print("Name of the student: ",sub)
    for j in range(number_of_subjects):
        print(subj_up[g],grades_matrix[ind_s][g])
    print("\n")
    chose=int(input("Please select an option: "))

#Option 5: Exit
 if chose==5:
  print("Exit")
  break

Introduce the number of students: 2
Introduce the number of subjects: 3
Name of the student 1: Pau
Name of the student 2: Lu
Name of the subject 1: Python
Name of the subject 2: Java
Name of the subject 3: C++
['Pau', 'Lu']
['Python', 'Java', 'C++']
Please,enter the grade for the student 1 in the subject 1: 2
[[2. 0. 0.]
 [0. 0. 0.]]
Please,enter the grade for the student 1 in the subject 2: 3
[[2. 3. 0.]
 [0. 0. 0.]]
Please,enter the grade for the student 1 in the subject 3: 4
[[2. 3. 4.]
 [0. 0. 0.]]
Please,enter the grade for the student 2 in the subject 1: 5
[[2. 3. 4.]
 [5. 0. 0.]]
Please,enter the grade for the student 2 in the subject 2: 6
[[2. 3. 4.]
 [5. 6. 0.]]
Please,enter the grade for the student 2 in the subject 3: 7
[[2. 3. 4.]
 [5. 6. 7.]]


MENU
1) Average Grade - Subject
2) Average Grade - Student
3) Show Grades of all students
4) Show grades of a student
5) Sign Out
Please select an option: 1
Please, enter the name of the subject: Java
The average of this subject is:

### 